package socket;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dell-pc
 */
public class JClient extends javax.swing.JFrame {

    String name;
    Socket s1;
    BufferedReader reader;
    PrintWriter writer;
    /**
     * Creates new form Jrun
     */
    public JClient(String name, Boolean at,Boolean bt,Boolean ct) {
        this.name = name;

        initComponents();
        jtfcliname.setText("客户端" + name);
        try {
            s1 = new Socket("127.0.0.1", 8888);
            reader = new BufferedReader(new InputStreamReader(s1.getInputStream()));
            writer = new PrintWriter(s1.getOutputStream(), true);
            //发送给服务器端
            writer.println(name);
//                System.out.println(aisLogin);


            this.setVisible(true);

            //接受服务器发过来的 在线用户消息
//            list = socket.getList();
//            
//            
//            ////判断其他是否在线，并设置颜色
//                for (int i = 0; i < list.size; i++) {
//                    if(list[i].eqals("at"))
//                    btncliA.setBackground(Color.green);
//                    if(list[i].eqals("at"))
//                    btncliA.setBackground(Color.green);
//                    if(list[i].eqals("at"))
//                    btncliA.setBackground(Color.green);
//                }




        } catch (IOException ex) {

        }

    }

    public JClient(String name) {
        this.name = name;

        initComponents();
        jtfcliname.setText("客户端" + name);
        try {
            //获得一个连接服务器的socket
            s1 = new Socket("127.0.0.1", 8888);
            //输入流
            reader = new BufferedReader(new InputStreamReader(s1.getInputStream()));
            //输出流，自动flush
            writer = new PrintWriter(s1.getOutputStream(), true);
            //发送给服务器端
            writer.println(name);
//            System.out.println("ok!----");
            this.setVisible(true);
            //监听上线用户的线程
            new Thread(() -> {
                while (true) {
                    try {
                        String cname = reader.readLine();
                        System.out.println("connected!");
                        //拆分逗号，得到A B C
                        String[] cn = cname.split(",");
                        //迭代判断设置按钮颜色
                        for (String aCn : cn) {
                            if (aCn.equals("A")) this.btncliA.setBackground(Color.green);
                            if (aCn.equals("B")) this.btncliB.setBackground(Color.green);
                            if (aCn.equals("C")) this.btncliC.setBackground(Color.green);
                        }
                        System.out.println("Client name:" + cname);

                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }).start();

        } catch (IOException ex) {

        }

    }


    private JClient() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btncliA = new javax.swing.JButton();
        btncliB = new javax.swing.JButton();
        btncliC = new javax.swing.JButton();
        jtfcliname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("退出登陆");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btncliA.setBackground(new java.awt.Color(255, 0, 0));
        btncliA.setText("客户端A");
        btncliA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncliAActionPerformed(evt);
            }
        });

        btncliB.setBackground(new java.awt.Color(255, 0, 0));
        btncliB.setText("客户端B");
        btncliB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncliBActionPerformed(evt);
            }
        });

        btncliC.setBackground(new java.awt.Color(240, 0, 0));
        btncliC.setText("客户端C");

        jtfcliname.setEditable(false);
        jtfcliname.setText("jTextField1");
        jtfcliname.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jtfcliname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btncliB)
                                        .addComponent(btncliA)
                                        .addComponent(btncliC))
                                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(btncliA))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(jtfcliname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addComponent(btncliB)
                                .addGap(20, 20, 20)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncliC)
                                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btncliAActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btncliBActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
        this.dispose();
        new Jlogin().setVisible(true);
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btncliA;
    private javax.swing.JButton btncliB;
    private javax.swing.JButton btncliC;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jtfcliname;
    // End of variables declaration                   
    public JButton getbtncliA() {
        return btncliA;
    }

    public JButton getbtncliB() {
        return btncliB;
    }

    public JButton getbtncliC() {
        return btncliC;
    }
}